# Site settings
title: OPEN-BOOK-STACK
description: A Collection all Resources across all Domains by various Contributors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://openbookstack.github.io/open.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Open-Book-Stack
user_description: Developer
email: sathuribharath@gmail.com
twitter_username: bharathsathuri
github_username:  OpenBookStack
gplus_username:  bharathsathuri
disqus_username: openbookstack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-admin

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Contribute
    url: /contribute
  - title: Series
    url: /series
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
